# Generated by Django 2.1.3 on 2018-12-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtext',
            field=models.CharField(default='', max_length=200),
        ),
    ]
